# Generated by Django 5.2.4 on 2025-08-08 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_chat_sessions',
                'indexes': [models.Index(fields=['user_id'], name='user_chat_s_user_id_660d99_idx'), models.Index(fields=['session_id'], name='user_chat_s_session_3ba71b_idx'), models.Index(fields=['last_activity'], name='user_chat_s_last_ac_39cd5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('medical_report', 'Medical Report'), ('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('imaging', 'Imaging Report'), ('other', 'Other')], default='other', max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('vector_ids', models.JSONField(default=list)),
                ('extracted_text', models.TextField(blank=True)),
                ('processing_status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'user_documents',
                'indexes': [models.Index(fields=['user_id'], name='user_docume_user_id_d2c900_idx'), models.Index(fields=['upload_date'], name='user_docume_upload__4e7fe3_idx'), models.Index(fields=['document_type'], name='user_docume_documen_734e21_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('assistant', 'Assistant Response'), ('system', 'System Message')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.userchatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'indexes': [models.Index(fields=['session'], name='chat_messag_session_70d2c0_idx'), models.Index(fields=['timestamp'], name='chat_messag_timesta_93c8bf_idx'), models.Index(fields=['message_type'], name='chat_messag_message_b8fb34_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('text_content', models.TextField()),
                ('vector_id', models.CharField(max_length=255, unique=True)),
                ('embedding_model', models.CharField(default='text-embedding-ada-002', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.userdocument')),
            ],
            options={
                'db_table': 'document_chunks',
                'indexes': [models.Index(fields=['document'], name='document_ch_documen_53de58_idx'), models.Index(fields=['vector_id'], name='document_ch_vector__133003_idx')],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
